version: 2.1
workflows:
  docker_build_push:
    jobs:
      - build:
          context: trail # has an env var called MY_ENV_VAR


jobs:
  build:
    working_directory: /app
    docker:
      - image: cimg/base:2021.11
        auth:
            username: raghumanne
            password: $DOCKERHUB_PASSWORD
  push:          
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=app -t raghumanne/circleci:${CIRCLE_SHA1} .
      - run:
          name: Listing docker images
          command: |
            docker images
            docker push raghumanne/circleci:$CIRCLE_SHA1